// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhbhdgnqrbvcuoizemrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oYmhkZ25xcmJ2Y3VvaXplbXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NzI0OTgsImV4cCI6MjA1MzI0ODQ5OH0.TduHnTTNyyQbdSxk9tij2YGUFHjbg4K55Dvwsqm330Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);