
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bojggtnrrbngyvzjerme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvamdndG5ycmJuZ3l2emplcm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzM0MjEsImV4cCI6MjA1OTcwOTQyMX0.ntyBg-Uv5V5bILQ13TBTxErpYa6QEnqIQkbFgcyD-hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Use localStorage for session persistence
    persistSession: true, // Ensure session persistence
    autoRefreshToken: true, // Automatically refresh tokens
    detectSessionInUrl: true, // Detect session from URL (e.g., for OAuth redirects)
  },
});

